{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentflow.fullname" . }}
  labels:
    {{- include "agentflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ include "agentflow.dbUser" . | quote }}
  password: {{ include "agentflow.dbPassword" . | quote }}
  jdbc-url: {{ include "agentflow.jdbcUrl" . | quote }}
  sqlalchemy-url: {{ include "agentflow.sqlalchemyUrl" . | quote }}
  redis-host: {{ include "agentflow.redisHost" . | quote }}
  redis-port: {{ include "agentflow.redisPort" . | quote }}
  redis-url: {{ include "agentflow.redisUrl" . | quote }}
{{- end }}
